version: '3.1'
services:
  mylegendapi:
    image: dockervisakh/legendimg:latest
    restart: always
    ports: 
      - 81:81
  mysportapi:
    image: dockervisakh/sportimg:latest
    restart: always
    ports:
      - 80:80
  mymongo:
    image: dockervisakh/mongoapp:latest
    restart: always
    volumes:
      - mymongodata:/data/db
  mymongoexp:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mymongo
volumes:
  mymongodata:
    driver: local
