apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  serviceName: {{ .Values.app.sname }}
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          volumeMounts:
            - name: {{ .Values.app.pvcname }}
              mountPath: "/data/db"
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.app.pvcname }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: do-block-storage
