name: Deploy Docker Compose

on:
  push:
    branches:
      - main

env:
  SERVER_IP: 165.22.210.88

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo apt-get update
          docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
          cd PY-MicroService
          git pull origin main
          docker compose down
          docker compose up -d
          
          
