name: Build the image, Push to registry, Deploy - Legend

on:
  push:
    branches:
      - main
    paths:
      - LegendApi/**

env:
  DOCKER_IMAGE: dockervisakh/legendimg
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "$DOCKER_IMAGE:$DOCKER_TAG"
