name: Build the image, Push to registry, Deploy - Sport

on:
  push:
    branches:
      - main
    paths:
      - SportApi/**

jobs:
  build-and-push-to-registry:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:SportApi"
          push: true
          tags: dockervisakh/sportimg:latest
